services:
  api-gateway:
    build: ./api-gateway
    ports:
      - '5000:5000'
    env_file: ./api-gateway/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  user-service:
    build: ./user-service
    env_file: ./user-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  post-service:
    build: ./post-service
    env_file: ./post-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  media-service:
    build: ./media-service
    env_file: ./media-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  search-service:
    build: ./search-service
    env_file: ./search-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - app-network

  networks:
    app-network:
